const {spawn}=require('node:child_process');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const assert=require('node:assert/strict');
// Run only against tools/preview_stone_map.py (temporary accounts and media).
// Direct CDP supports Chromium 78; current Playwright requires newer protocol methods.
const targetURL = new URL(process.env.STONE_QA_URL);
assert.ok(['127.0.0.1', 'localhost'].includes(targetURL.hostname) && targetURL.port !== '18050', 'Use an isolated loopback preview');
assert.ok(process.env.CHROMIUM78_EXECUTABLE, 'Set CHROMIUM78_EXECUTABLE');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'tigertales-78-evidence-'));
const width=Number(process.env.STONE_QA_WIDTH || 390);
const height=Number(process.env.STONE_QA_HEIGHT || 844);
const child=spawn(process.env.CHROMIUM78_EXECUTABLE,['--headless','--disable-gpu','--no-first-run','--remote-debugging-port=0',`--user-data-dir=${fs.mkdtempSync(path.join(os.tmpdir(),'tigertales-78-qa-'))}`],{windowsHide:true});
let socket;
let send;
const errors=[];
(async()=>{
 const address=await new Promise((resolve,reject)=>{let log='';child.stderr.on('data',chunk=>{log+=chunk;const match=log.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(match)resolve(match[1]);});child.on('error',reject);});
 socket=new WebSocket(address);
 await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});
 let id=0;const pending=new Map();
 socket.onmessage=event=>{const data=JSON.parse(event.data);if(data.id){const job=pending.get(data.id);pending.delete(data.id);data.error?job.reject(new Error(JSON.stringify(data.error))):job.resolve(data.result);}else if(data.method==='Runtime.exceptionThrown') errors.push(data.params.exceptionDetails.exception?.description||data.params.exceptionDetails.text);};
 send=(method,params={},sessionId)=>new Promise((resolve,reject)=>{const key=++id;pending.set(key,{resolve,reject});socket.send(JSON.stringify({id:key,method,params,sessionId}));});
 const version=await send('Browser.getVersion');
 assert.match(version.product, /Chrome\/78\./);
 console.log(version.product);
 const {targetId}=await send('Target.createTarget',{url:'about:blank'});
 const {sessionId}=await send('Target.attachToTarget',{targetId,flatten:true});
 const call=(method,params)=>send(method,params,sessionId);
 const evaluate=async expression=>{const value=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(value.exceptionDetails)throw new Error(value.exceptionDetails.exception.description);return value.result.value;};
 const wait=async expression=>{for(let i=0;i<300;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100));}throw new Error('Timed out: '+expression);};
 await call('Runtime.enable');await call('Page.enable');
 await call('Emulation.setDeviceMetricsOverride',{width,height,mobile:width<768,deviceScaleFactor:1});
 await call('Page.navigate',{url:targetURL.href});
  await wait('document.querySelectorAll(".stone-lesson").length===30 && document.getElementById("map-loading").classList.contains("hidden")');
  await wait('document.querySelector(".bg-layer__slide").dataset.art === "map"');
  const geometry=await evaluate(`(() => {
    const frame=document.querySelector('.stone-frame');
    const first=document.querySelectorAll('.stone-lesson')[0].getBoundingClientRect();
    const second=document.querySelectorAll('.stone-lesson')[1].getBoundingClientRect();
    const style=getComputedStyle(frame);
    return {width:innerWidth,scroll:document.body.scrollWidth,frameWidth:parseFloat(style.width),frameHeight:parseFloat(style.height),gap:second.top-first.bottom};
  })()`);
  assert.ok(geometry.scroll <= geometry.width);
  assert.ok(geometry.frameWidth >= 180 && Math.abs(geometry.frameWidth / geometry.frameHeight - 16/9) < .02);
  assert.ok(geometry.gap >= (width < 768 ? 193 : 215));
  console.log({geometry,output:root});
  fs.writeFileSync(path.join(root,'map.png'),Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
  await evaluate('document.getElementById("user-menu-trigger").click()');
  assert.equal(await evaluate('document.getElementById("user-menu-popup").style.display'),'block');
  await evaluate('document.getElementById("profile-open").click()');
  assert.equal(await evaluate('document.getElementById("profile-dialog").open'),true);
  await evaluate('document.getElementById("profile-cancel").click()');
  await evaluate('document.querySelector(".stone-lesson").click()');
  assert.equal(await evaluate('document.getElementById("detail-title").textContent'),'The Apple, Please');
  fs.writeFileSync(path.join(root,'detail.png'),Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
  await evaluate('document.getElementById("back-btn").click();document.getElementById("adventure-menu-button").click()');
  assert.equal(await evaluate('document.getElementById("course-drawer").hidden'),false);
  assert.ok(await evaluate('document.getElementById("course-drawer").getBoundingClientRect().bottom <= innerHeight'));
  fs.writeFileSync(path.join(root,'drawer.png'),Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
  assert.deepEqual(errors,[]);
  console.log('PASS: 30 lessons, artwork, account, profile, lesson, course drawer; no runtime errors');
})().catch(error=>{console.error(error,errors);process.exitCode=1;}).finally(async()=>{if(send)await send('Browser.close').catch(()=>{});if(socket)socket.close();child.kill();});
