"""Export delivery WebP assets without changing the PNG artwork sources.

Run from the repo root: app/.venv/Scripts/python tools/optimize_map_assets.py
This is an asset maintenance command, not an application build step.
"""
import hashlib
import io
import json
from pathlib import Path

from PIL import Image


def main():
    static = Path(__file__).resolve().parents[1] / 'app' / 'static'
    output = static / 'map-assets'
    output.mkdir(exist_ok=True)
    sources = sorted((static / 'worlds-map').glob('*.png'))
    sources += [static / 'stone-map' / f'{name}.png' for name in ('paver', 'pedestal', 'star')]
    sizes = {'terrain': (512, 512), 'paver': (204, 132), 'pedestal': (1320, 475), 'star': (306, 306)}
    manifest = {}
    before = after = 0
    for source in sources:
        with Image.open(source) as image:
            if source.stem in sizes:
                image.thumbnail(sizes[source.stem], Image.Resampling.LANCZOS)
            buffer = io.BytesIO()
            image.save(buffer, format='WEBP', quality=92, method=6)
        data = buffer.getvalue()
        digest = hashlib.sha256(data).hexdigest()[:16]
        filename = f'{source.parent.name}-{source.stem}.{digest}.webp'
        (output / filename).write_bytes(data)
        manifest['/static/' + source.relative_to(static).as_posix()] = '/static/map-assets/' + filename
        before += source.stat().st_size
        after += len(data)
    (static / 'map-assets.mjs').write_text(
        '// Generated by tools/optimize_map_assets.py; keep the source PNG artwork.\n'
        + 'export const MAP_ASSETS = Object.freeze(' + json.dumps(manifest, indent=2) + ');\n'
        + 'export const mapAsset = source => MAP_ASSETS[source] || source;\n', encoding='utf-8')
    # A separate generated stylesheet overrides only image URLs, never layout.
    (static / 'map-assets.css').write_text(
        '/* Generated delivery assets; geometry and shadows stay in stone-map.css. */\n'
        + '.stone-map #bg-layer { background-image: url("' + manifest['/static/worlds-map/terrain.png'] + '"); }\n'
        + '.stone-pedestal { background-image: url("' + manifest['/static/stone-map/pedestal.png'] + '"); }\n'
        + '.stone-title { background-image: linear-gradient(#fff0d3b3,#e4cda3d9), url("' + manifest['/static/stone-map/pedestal.png'] + '"); }\n', encoding='utf-8')
    print(f'{len(manifest)} assets: {before / 1e6:.2f} MB -> {after / 1e6:.2f} MB', flush=True)


if __name__ == '__main__':
    main()
